language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y gettext nasm
- chmod -R 777 *
script:
- mkdir build target
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=../target -DBUILD_ROK4=TRUE -DBUILD_BE4=FALSE -DBUILD_DOC=FALSE
  -DUNITTEST=false -DDEBUG_BUILD=FALSE
- make package
- export FILE_TOUPLOAD=$(find ./ -maxdepth 1 -name "Rok4*.tar.gz")
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $FILE_TOUPLOAD
  on:
    repo: rok4/rok4
    tags: true
